# Generated by Django 3.1.1 on 2020-10-02 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boast',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='roast',
            name='down_votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roast',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
